### ISSUE TITLE
Victors bild funkar inte

### ISSUE THREAD

**Issue by Matin051** [VBDojnaz/YTMVP2-Hackathon#11]
Victor var så dum så att han glömde punkten innan /
Det ska vara `./victor.jpg`, men han skrev istället `/victor.jpg` [victor_back.html#L9](https://github.com/VBDojnaz/YTMVP2-Hackathon/blob/b0ec530bfaca07c3e6fb04e770809058a5becfc1/victor_back.html#L9)

**Comment by VeeBack** [comment]
😠
